from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO

def generate_pdf_report(data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("CodeBurnout AI Report", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"Username: {data.get('username','N/A')}", styles["Normal"]))
    story.append(Paragraph(f"Score: {data['result']['score']}", styles["Normal"]))
    story.append(Paragraph(f"Level: {data['result']['level']}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Generated by CodeBurnout AI", styles["Italic"]))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()